export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const RESET_COUNTER = 'RESET_COUNTER';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const MOUSE_SCROLLED = 'MOUSE_SCROLLED';
export const UPDATE_DISPLAY_LIST = 'UPDATE_DISPLAY_LIST';
export const SORT_DISPLAY_LIST = 'SORT_DISPLAY_LIST';
